Stripping channel whitesapce
lrnselfreliance/wrolpi pull request #95
Opened 2022-02-07 18:11 UTC by StruckCroissant

fixes #51 
Added whitespace strip to channel apy.py file via dict copy & edit

2022-02-07 18:44 UTC, lrnselfreliance commented
@StruckCroissant I don't see the changes in this PR.  Check that you've pushed the correct branch?

2022-02-07 18:58 UTC, StruckCroissant commented
@lrnselfreliance forgot to push local commits to remote branch. Fixed

2022-02-07 19:08 UTC, lrnselfreliance requested changes
Also, modify a channel test to check that the name is stripped.  I suggest adding it here: `modules.videos.channel.test.test_api.TestVideoAPI.test_channel`

In the test, modify "Example Channel 1" to include some whitespace, then assert that it is stripped later in the test.

2022-02-07 19:08 UTC, lrnselfreliance commented on modules/videos/channel/api.py
> +    print(channel)
Remove this print.

2022-02-07 19:52 UTC, StruckCroissant commented on modules/videos/channel/api.py
> +    print(channel)
fixed

2022-02-13 06:13 UTC, StruckCroissant commented
@lrnselfreliance Added channel whitespace test into test_api,py

2022-02-13 15:14 UTC, lrnselfreliance approved these changes

2022-02-13 15:14 UTC, merged